### ISSUE TITLE
Slurm Munge keys

### ISSUE THREAD

**Issue by jeremypmann** [OSC/Open-OnDemand#50]
The documentation says OnDemand needs the proper Munge keys to display cluster information but just what does that mean? How do I import the local munge key to my ondemand portal node?

**Comment by treydock** [comment]
@jeremypmann You have to configure Munge on the OnDemand node just like you would any other cluster node.  This means /etc/munge/munge.key must match the key used on the cluster and the munge service needs to be running.

**Comment by jeremypmann** [comment]
On the portal node I set all of that up and am able to run sinfo and sbatch to check node status and submit jobs. But when I go to the OOD portal and click on Jobs -> Job Composer it says "There are no configured hosts that allow you to submit jobs. Please contact your system administrator."

**Comment by treydock** [comment]
Do you have clusters defined per https://osc.github.io/ood-documentation/master/installation/add-cluster-config.html ?  There is a check for cluster that is likely generating the error: https://github.com/OSC/ood-myjobs/blob/master/app/controllers/workflows_controller.rb#L7-L9.  

Really basic example:

```yaml
---
v2:
  metadata:
    title: "Example Cluster"
  login:
    host: "head"
  job:
    adapter: "slurm"
    bin: "/opt/slurm/bin"
    conf: "/opt/slurm/etc/slurm.conf"
```
