### ISSUE TITLE
Ondemand on non HPC servers

### ISSUE THREAD

**Issue by puneet336** [OSC/Open-OnDemand#54]
Hi, 
Q1. Is it possible to host the openondemand application on a server which doesn't have direct access to the job scheduler config/commands (but can reach it via ssh)? 

example -  
      Machine A <-----(ssh:22)-------> [Master node <-----------> compute node]

In aforementioned scenario, can we host openondemand on Machine A?

Q2.  similarity, can we setup the openondemand  for two clusters having different job schedulers? 
example - 
[Master Node(PBS)] <------(ssh:22)------->Machine A <------(ssh:22)------->[Master Node (slurm)]

can  openondemand manage two clusters from Machine A?

**Comment by ericfranz** [comment]
If your scheduler is Slurm, LSF, PBSPro, or SGE, it should be possible by writing wrapper script for each of the programs these use.

See https://osc.github.io/ood-documentation/master/installation/resource-manager/slurm.html for a short explanation of the bin_overrides configuration option. Another approach is to just specify the bin path to a directory that contains all of the wrapper scripts.

For example, an squeue wrapper script would successfully:

1. pass all the arguments to it to squeue via ssh
2. direct stdin to the squeue command via ssh
3. direct stdout and stderr from the squeue via ssh to stdout/stderr
4. exit with the same exit status as the squeue via ssh command does

If you have success with this, please share the wrapper scripts you write as it would be very valuable for the community. @MorganRodgers or I could try to help as well.

**Comment by puneet336** [comment]
thank you @ericfranz , advice was very helpful.
 After installing OOD on MachineA - 

1. created few wrappers for "quick tests" -[ view ](https://github.com/puneet336/OOD-1.5_wrappers/tree/master/openondemand/1.5/wrappers/slurm) .

2. created cluster config file for ood ( /etc/ood/config/clusters.d/SLURM_CLUSTER1.yml ) as - 

```
---
v2:
  metadata:
    title: "ClusterProxy4-199"
  login:
    host: "masternodecluster1"
  job:
    adapter: "slurm"
    cluster: "slurm_cluster"
    bin: "/home/apps/SiteSoftwares/openondemand/1.5/wrappers/slurm/bin"
    conf: "/home/apps/SiteSoftwares/openondemand/1.5/wrappers/slurm/etc/slurm.conf"
    # bin_overrides:
      # sbatch: "/usr/local/bin/sbatch"
      # squeue: ""
      # scontrol: ""
```

job submission,cancellation & listing jobs+details (active jobs) is working fine.
I am able to get shell on master node.


Will check jupyter notebook accessibility and update. I have following URLs which i'll follow for jupyter notebook setup .

https://osc.github.io/ood-documentation/master/app-development/interactive/setup/enable-reverse-proxy.html
https://osc.github.io/ood-documentation/master/app-development/tutorials-interactive-apps/add-jupyter/copy-app.html
https://osc.github.io/ood-documentation/master/app-development/tutorials-interactive-apps/add-jupyter/customize-attributes.html


If i need to do some more configurations/ follow additional steps on my current setup, please let me know -
